Fix startup bug due to old node version
Solution as suggested by @kpcyrd.

Fixed behaviour:

    $ docker logs <CONTAINER>

    /cryptpad/server.js:44
                for (let header in h) { res.setHeader(header, h[header]); }
                     ^^^

    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Function.Module.runMain (module.js:442:10)
        at startup (node.js:136:18)
        at node.js:966:3